version: '3.8'

services:
  api:
    build: .
    container_name: nest-api
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=pruebaCrud
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pruebaCrud
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build: ../appfront
    container_name: react-frontend
    ports:
       - '3002:80'
    stdin_open: true
    tty: true
    depends_on:
      - api
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
